### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by sherriff** [Cantara/ConfigService#20]
1. Create (and document) a data model suited to the problem, think about the usage patterns 
2. Persist ServiceConfig, ClientConfig and client envInfo. 

Graph database, Neo4j looks like the most appropriate:
https://wiki.cantara.no/display/dev/ConfigService+persistence
Discuss with Totto and Erik.

**Comment by totto** [comment]
KISS version:  

FileOutputStream fos = new FileOutputStream("map.ser");
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(map);
        oos.close();

        FileInputStream fis = new FileInputStream("map.ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        Map anotherMap = (Map) ois.readObject();
        ois.close();

read in InMemConfigRepo constructor  .. write on changes/updates

**Comment by jorunfa** [comment]
Jeg er egentlig litt enig der med @totto. Vi skriver himla sjeldent p.t., så jeg tror dette kan holde en god stund. :+1:

**Comment by sherriff** [comment]
Helt greit å gjøre det først, men tviler på om utvidelser av modellen er hensiktsmessig/lett å lage uten å få inn grafmodellen, men det ser vi. Uansett liten kostnad å bare lage triviell persistens først.

**Comment by jorunfa** [comment]
Det eneste jeg ikke er 100% sikker på er hvordan vi gjør det med Docker, for å faktisk få det til å bli lagret. Men det er vel bare et lite parameter eller noe?

**Comment by sherriff** [comment]
Data volume container. Se f.eks. på https://github.com/Cantara/maven-infrastructure/tree/master/nexus.

**Comment by sherriff** [comment]
Den enkle varianten er implement. Lager nytt issue for grafbasert lagring.
