### ISSUE TITLE
Admin role for all endpoints not used by JAU/Configured applications

### ISSUE THREAD

**Issue by sherriff** [Cantara/ConfigService#40]
1. Review which endpoints are used by JAU or configured applications and update https://wiki.cantara.no/display/dev/ConfigService+API. 
2. Add admin role with separate http basic auth user to separate the access control.

**Comment by awillersud** [comment]
Endpoints used by JAU or configured applications are the just the following:
POST /client/registration
POST /client/{clientId}/sync

However Jetty only supports very basic path matching (wildcard at the beginning of the url or wildcard at end). This means we cannot separate between /client/{clientId}/sync and the other /client/ endpoints: https://wiki.cantara.no/display/dev/ConfigService+API.

Adding admin role and restricting the current user role to /client/* paths.

**Comment by awillersud** [comment]
**2.2 Servlet API**
Path specifications can be of the following forms:

```
/foo/bar           - an exact path specification.
/foo/*             - a prefix path specification (must end '/*').
*.ext              - a suffix path specification.
/                  - the default path specification.
""                 - the / path specification
```

**Comment by awillersud** [comment]
Restricting /application endpoints to admin role by servlet filter.

Implemented programmatic check for admin role in all /client endpoints except /client/registration and /client/{clientId}/sync.
