### ISSUE TITLE
Local config is not updated when config is changed.

### ISSUE THREAD

**Issue by baardl** [Cantara/ConfigService#42]
When updating applicationconfig with new json: 
.....
"lastChanged": "2016-05-26T08:54:18.994Z",
.....
Endpoint used: 'http://localhost:8086/jau/application/784e48f3-c6a7-48a8-8d97-9a2c1e032320/config'

When client connects:
09:03:57.397 [qtp1511785794-17] TRACE no.cantara.cs.client.ClientResource - checkForUpdate with clientId=33cb048b-ba39-4275-97fa-b4727a85d830
09:03:57.398 [qtp1511785794-17] TRACE no.cantara.cs.client.ClientResource - ClientConfig has not changed, return 204 No Content configLastChanged=2016-05-25T18:47:18.994Z

Assume this is a bug?
Version: Latest on JAU and CS

**Comment by awillersud** [comment]
For å oppdatere config må du bruke PUT application/{applicationId}/config/{configId}. Fra beskrivelsen ser det kanskje ut som du brukte POST application/{applicationId}/config, isåfall får du en ny config. Eksisterende klienter vil kun oppdateres hvis deres konfig blir oppdatert, ikke hvis applikasjonen får en ny default config.

For å se hvilken config som er gjeldende default for en applikasjon kan du gjøre GET application/{applicationId}/config. Id fra den bør være samme som applicationConfigId i Client, sjekk med GET client/33cb048b-ba39-4275-97fa-b4727a85d830. Hvis ikke kan du enten gjøre PUT på client/{clientId} og oppdatere til riktig applicationConfigId eller gjøre PUT på applicationConfig.

**Comment by baardl** [comment]
Hei.

Dette var ikke så innlysende. Fra denne:
http://restcookbook.com/HTTP%20Methods/put-vs-post/
PUT = create
POST = update

PUT for update høres ikke logisk ut.
Kan du forklare om dette er meningen, og hvorfor?

Bård

**Comment by awillersud** [comment]
Du har miksa de :)

PUT er create or update (og klient bestemmer id)
POST er create (og server bestemmer id)

**Comment by baardl** [comment]
Så PUT er erstatt allt, og du kjenner id'n.
POST er delvis oppdatering.
