### ISSUE TITLE
Support http proxy for ConfigServiceClient and DownloadUtil

### ISSUE THREAD

**Issue by sherriff** [Cantara/ConfigService#9]

**Comment by totto** [comment]
command-line:
java -Dhttp.proxyHost=10.246 or 

encoronment:
cat "etc_environment_append_nmd.txt" >>/home/avb/.bash_profile
http_proxy="http://10.246.xx:8080/"
HTTP_PROXY="http://10.246.xx:8080/"
https_proxy="https://10.246.xx:8080/"
HTTPS_PROXY="https://10.246.xx:8080/"
ftp_proxy="ftp://10.246.xx:8080/"
FTP_PROXY="ftp://10.246xx:8080/"
export no_proxy=localhost,127.0.0.1
export http_proxy

or java-code:
public void setProxy() {
    if (isUseHTTPProxy()) {
        // HTTP/HTTPS Proxy
        System.setProperty("http.proxyHost", getHTTPHost());
        System.setProperty("http.proxyPort", getHTTPPort());
        System.setProperty("https.proxyHost", getHTTPHost());
        System.setProperty("https.proxyPort", getHTTPPort());
        if (isUseHTTPAuth()) {
            String encoded = new String(Base64.encodeBase64((getHTTPUsername() + ":" + getHTTPPassword()).getBytes()));
            con.setRequestProperty("Proxy-Authorization", "Basic " + encoded);
            Authenticator.setDefault(new ProxyAuth(getHTTPUsername(), getHTTPPassword()));
        }
    }
    if (isUseSOCKSProxy()) {
        // SOCKS Proxy
        System.setProperty("socksProxyHost", getSOCKSHost());
        System.setProperty("socksProxyPort", getSOCKSPort());
        if (isUseSOCKSAuth()) {
            System.setProperty("java.net.socks.username", getSOCKSUsername());
            System.setProperty("java.net.socks.password", getSOCKSPassword());
            Authenticator.setDefault(new ProxyAuth(getSOCKSUsername(), getSOCKSPassword()));
        }
    }
}

...

public class ProxyAuth extends Authenticator {
    private PasswordAuthentication auth;

    private ProxyAuth(String user, String password) {
        auth = new PasswordAuthentication(user, password == null ? new char[]{} : password.toCharArray());
    }

    protected PasswordAuthentication getPasswordAuthentication() {
        return auth;
    }
}

**Comment by jorunfa** [comment]
This issue is solved, and it is possible to set proxy through properties. Ideally we should maybe also be able to get proxy settings from Internet Explorer, but that is another issue.
